[2022-03-29T15:29:01.066] [ERROR] error - error = Error: Access denied for user 'orbiter'@'localhost' to database 'orbiter'
    at Packet.asError (/Users/zhouxy/work/project/orbiter/project/NetWorkStatus/node_modules/mysql2/lib/packets/packet.js:728:17)
    at ClientHandshake.execute (/Users/zhouxy/work/project/orbiter/project/NetWorkStatus/node_modules/mysql2/lib/commands/command.js:29:26)
    at PoolConnection.handlePacket (/Users/zhouxy/work/project/orbiter/project/NetWorkStatus/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (/Users/zhouxy/work/project/orbiter/project/NetWorkStatus/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart (/Users/zhouxy/work/project/orbiter/project/NetWorkStatus/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/zhouxy/work/project/orbiter/project/NetWorkStatus/node_modules/mysql2/lib/connection.js:92:25)
    at Socket.emit (events.js:314:20)
    at Socket.EventEmitter.emit (domain.js:486:12)
    at addChunk (_stream_readable.js:307:12)
    at readableAddChunk (_stream_readable.js:282:9) {
  code: 'ER_DBACCESS_DENIED_ERROR',
  errno: 1044,
  sqlState: '42000',
  sqlMessage: "Access denied for user 'orbiter'@'localhost' to database 'orbiter'",
  sql: undefined
}
